### ISSUE TITLE
Add the app's id (PK) to the /apps endpoint JSON output

### ISSUE THREAD

**Issue by mslatour** [PerceptumNL/edubox-platform#47]

**Comment by mslatour** [comment]
The problem with this is that there is no such thing as a PK for the elements returned by the apps endpoint, since those are not apps but app views. Which app views are returned by the endpoint are determined at runtime for a specific user, and are not stored as such in a database table. So the identifier for a view probably needs to be composed of other persistent information, like `"{{group}}:{{app}}"`

**Comment by tdoolan** [comment]
Is this solved by a94d8034c30c82d9cd5b6869bae5e77a56e93186 and subsequent commits?

I assume the id's were needed to generate the link, but now the endpoint already returns the link directly
